"""
Agent State Definition for WebClaw DeepAgent

This module defines the data structures that represent the agent's state
as it flows through the LangGraph execution pipeline.

Key Concepts:
- TypedDict: A Python type hint for dictionaries with specific key-value types
- BaseModel: Pydantic's base class for data validation and serialization
- AgentState: The main state container passed between agent nodes

Author: WebClaw Team
Version: 0.1.0
"""

from typing import TypedDict, List, Optional, Any
from pydantic import BaseModel, Field


class BrowserState(BaseModel):
    """
    Browser-specific state container.

    This class tracks the current state of the Playwright browser instance,
    including the URL, page content, and visual state.

    Attributes:
        current_url (str): The URL of the currently loaded page.
                           Empty string if no page is loaded.
        page_title (str): The title of the current web page.
        dom_content (str): A snapshot of the page's DOM content for analysis.
        screenshot_path (str): Path to the most recent screenshot file.
        elements_found (List[dict]): List of interactive elements found on page.

    Example:
        >>> browser_state = BrowserState(
        ...     current_url="https://www.baidu.com",
        ...     page_title="百度一下"
        ... )
    """
    current_url: str = ""
    page_title: str = ""
    dom_content: str = ""
    screenshot_path: str = ""
    elements_found: List[dict] = Field(default_factory=list)


class AgentState(TypedDict):
    """
    Main Agent State that flows through LangGraph execution graph.

    This TypedDict defines all the state variables that are passed between
    different agent nodes in the LangGraph pipeline. Each node can read
    and modify these values.

    LangGraph State Mechanics:
    - The state is immutable within a single node execution
    - Nodes return updates that are merged into the state
    - The state persists across the entire task execution

    Attributes:
        task (str): The user's original task/prompt to be executed.
        task_id (str): Unique identifier for tracking and logging purposes.

        current_step (int): Current execution step number (starts at 0).
                            Used to prevent infinite loops.
        max_steps (int): Maximum allowed steps to prevent runaway execution.
                         Default is 20 to balance thoroughness and cost.
        step_history (List[dict]): Complete history of all steps taken.
                                   Each entry contains: thought, action, result.

        browser_state (BrowserState): Current browser context including
                                      URL, title, DOM, and screenshots.

        thought (str): Agent's current reasoning/thinking process.
                       Generated by the LLM in each step.
        action (str): The specific action to be executed (e.g., "click", "type").
        action_result (str): The result/observation from executing the action.

        final_answer (str): The final output when task is successfully completed.
        success (bool): Boolean flag indicating task completion status.
        error_message (str): Error description if task execution failed.

        start_time (float): Unix timestamp when task execution began.
        end_time (Optional[float]): Unix timestamp when execution ended.
                                    None while task is still running.

    State Flow Example:
        Initial State → Planner Node → Executor Node → Critic Node → Final State

    Note:
        TypedDict is used instead of Pydantic BaseModel because LangGraph
        expects dictionary-style state that can be partially updated.
    """
    # Input Section - What the agent receives
    task: str                     # User's task/prompt description
    task_id: str                   # Unique identifier (e.g., "task_001")

    # Execution Tracking - Progress monitoring
    current_step: int              # Current step number (0, 1, 2, ...)
    max_steps: int                 # Maximum allowed steps (safety limit)
    step_history: List[dict]       # History of: {step, thought, action, result}

    # Browser Context - Current web page state
    browser_state: BrowserState    # Pydantic model with URL, title, DOM, etc.

    # Reasoning Section - LLM's thinking process
    thought: str                   # Agent's reasoning for current step
    action: str                    # Chosen action name (e.g., "click", "type")
    action_result: str             # Observation/result from action execution

    # Output Section - Final results
    final_answer: str              # Completed task output (if success)
    success: bool                  # True if task completed successfully
    error_message: str             # Error details (if failed)

    # Metadata - Timing information
    start_time: float              # Execution start timestamp
    end_time: Optional[float]      # Execution end timestamp (None if running)


def create_initial_state(task: str, task_id: str = "default") -> AgentState:
    """
    Factory function to create an initial AgentState for a new task.

    This function initializes all state fields with default values,
    setting up the foundation for the agent execution pipeline.

    Args:
        task (str): The user's task/prompt to be executed.
                    Example: "Open Baidu and search for Python tutorials"
        task_id (str): Unique identifier for this task instance.
                       Used for logging and tracking. Default: "default"

    Returns:
        AgentState: A new state dictionary ready for LangGraph execution.
                    All fields are initialized with sensible defaults.

    State Initialization Logic:
        - current_step = 0: Starting from scratch
        - max_steps = 20: Safety limit to prevent infinite loops
        - step_history = []: Empty history, will be populated during execution
        - browser_state = BrowserState(): Empty browser state, no page loaded
        - success = False: Initially marked as incomplete
        - start_time = current time: Mark execution beginning

    Example:
        >>> state = create_initial_state(
        ...     task="Open Baidu and search for Python",
        ...     task_id="test_001"
        ... )
        >>> print(state["task"])
        "Open Baidu and search for Python"
        >>> print(state["current_step"])
        0

    Usage in Agent Pipeline:
        state = create_initial_state(task)
        result_state = await agent.run(state)
        print(result_state["success"])
    """
    import time  # Import here to avoid top-level dependency

    return AgentState(
        # Input initialization
        task=task,
        task_id=task_id,

        # Execution tracking - start at step 0
        current_step=0,
        max_steps=20,  # Reasonable limit for most web tasks
        step_history=[],  # Empty history initially

        # Browser state - empty (no page loaded yet)
        browser_state=BrowserState(),

        # Reasoning - empty strings (will be filled by LLM)
        thought="",
        action="",
        action_result="",

        # Output - initially incomplete
        final_answer="",
        success=False,  # Will be set True when task completes
        error_message="",  # Will be set if execution fails

        # Metadata - record start time
        start_time=time.time(),  # Current Unix timestamp
        end_time=None  # Not ended yet
    )